# Generated by Django 2.2 on 2020-01-21 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
