# Generated by Django 2.2.10 on 2020-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200121_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='news', verbose_name='Imagen'),
        ),
    ]
