# Generated by Django 2.2.10 on 2020-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200212_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(help_text='Dimesiones recomendadas 750x350px o 640x299px', null=True, upload_to='news', verbose_name='Imagen'),
        ),
    ]
