# Generated by Django 2.2.10 on 2020-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200301_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(help_text='Ancho maximo recomendado 750px', null=True, upload_to='news', verbose_name='Imagen'),
        ),
    ]
