# Generated by Django 2.2.10 on 2020-02-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['created'], 'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
    ]
