# Generated by Django 2.2.10 on 2020-03-01 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200218_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Reseña Historica')),
                ('mision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mision')),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='vision')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
