# Generated by Django 2.2.10 on 2020-03-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nosotros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'ordering': ['updated'], 'verbose_name': 'nosotros', 'verbose_name_plural': 'nosotros'},
        ),
    ]
