# Generated by Django 2.2.10 on 2020-03-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nosotros_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='publidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='Core', verbose_name='Baner')),
                ('enlace', models.URLField(null=True, verbose_name='enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
