# Generated by Django 2.2.10 on 2020-03-02 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['created'], 'verbose_name': 'menú', 'verbose_name_plural': 'menú'},
        ),
        migrations.AlterModelOptions(
            name='publidad',
            options={'ordering': ['updated'], 'verbose_name': 'publidad', 'verbose_name_plural': 'publidad'},
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='visión'),
        ),
    ]
