# Generated by Django 2.2.10 on 2020-05-06 02:09

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Banco')),
            ],
        ),
        migrations.CreateModel(
            name='CapacidadPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Capacidad de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres y Apellidos')),
                ('grado', models.CharField(max_length=150, verbose_name='grado')),
                ('cedula', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=150, verbose_name='Telefono')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Opinión')),
            ],
        ),
        migrations.CreateModel(
            name='PlazoOrdinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Prestamo Ordinario')),
            ],
        ),
        migrations.CreateModel(
            name='PlazoTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Prestamo Ordinario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo de Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('cantidad_letras', models.CharField(max_length=150, verbose_name='Cantidad Letras')),
                ('cantidad_numeros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('casa_comercial', models.CharField(max_length=150, verbose_name='Nombre Casa Comercial')),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_solicitar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_aprobada', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capacidad_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.CapacidadPago', verbose_name='Capacidad de Pago')),
                ('opinion_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_otanalista', to='servicios.Opinion', verbose_name='Opinión del Analista')),
                ('opinion_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_otgerente', to='servicios.Opinion', verbose_name='Opinión del Gerente')),
                ('prestamo_tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.PlazoTienda', verbose_name='Prestamo Tienda Temporada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoOrdinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('cantidad_letras', models.CharField(max_length=150, verbose_name='Cantidad Letras')),
                ('cantidad_numeros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cuenta', models.CharField(max_length=150, verbose_name='N° Cuenta')),
                ('total_haberes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('cantidad_solicitar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Banco', verbose_name='Banco')),
                ('capacidad_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.CapacidadPago', verbose_name='Capacidad de Pago')),
                ('opinion_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_oanalista', to='servicios.Opinion', verbose_name='Opinión del Analista')),
                ('opinion_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_ogerente', to='servicios.Opinion', verbose_name='Opinión del Gerente')),
                ('prestamo_ordinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.PlazoOrdinario', verbose_name='Prestamo Ordinario')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.TipoCuenta', verbose_name='Tipo de Cuenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoAfianzado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('observaciones1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='1er Fiador')),
                ('observaciones2', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='2do Fiador')),
                ('observaciones3', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='3er Fiador')),
                ('observaciones4', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='4to Fiador')),
                ('fiador1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_fiador1', to='servicios.Fiador', verbose_name='1er Fiador')),
                ('fiador2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_fiador2', to='servicios.Fiador', verbose_name='2do Fiador')),
                ('fiador3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_fiador3', to='servicios.Fiador', verbose_name='3er Fiador')),
                ('fiador4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_fiador4', to='servicios.Fiador', verbose_name='4to Fiador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
