# Generated by Django 2.2.10 on 2020-05-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacidadpago',
            options={'ordering': ['nombre'], 'verbose_name': 'Capacidad de pago', 'verbose_name_plural': 'Capacidad de pago'},
        ),
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['nombre'], 'verbose_name': 'Opinion', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AlterModelOptions(
            name='plazoordinario',
            options={'ordering': ['nombre'], 'verbose_name': 'Plazo Ordinario', 'verbose_name_plural': 'Plazos Ordinarios'},
        ),
        migrations.AlterModelOptions(
            name='plazotienda',
            options={'ordering': ['nombre'], 'verbose_name': 'Plazo Tienda', 'verbose_name_plural': 'Plazos Tiendas'},
        ),
        migrations.AlterModelOptions(
            name='prestamoordinario',
            options={'ordering': ['user'], 'verbose_name': 'Préstamo Ordinario', 'verbose_name_plural': 'Préstamos Ordinarios'},
        ),
        migrations.AlterModelOptions(
            name='prestamotienda',
            options={'ordering': ['user'], 'verbose_name': 'Préstamo Tienda-Temporada', 'verbose_name_plural': 'Préstamos Tienda-Temporada'},
        ),
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de cuenta', 'verbose_name_plural': 'Tipos de cuenta'},
        ),
    ]
