# Generated by Django 2.2.10 on 2020-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20200506_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoordinario',
            name='ciudad',
            field=models.CharField(default='', max_length=150, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamoordinario',
            name='estado',
            field=models.CharField(default='', max_length=150, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamoordinario',
            name='faxofi',
            field=models.CharField(default='', max_length=150, verbose_name='Telf. fax'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamoordinario',
            name='tlfofi',
            field=models.CharField(default='', max_length=150, verbose_name='Telf. Ofic.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamoordinario',
            name='unidad',
            field=models.CharField(default='', max_length=150, verbose_name='Unidad/Dependencia donde labora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamotienda',
            name='ciudad',
            field=models.CharField(default='', max_length=150, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamotienda',
            name='estado',
            field=models.CharField(default='', max_length=150, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamotienda',
            name='faxofi',
            field=models.CharField(default='', max_length=150, verbose_name='Telf. fax'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamotienda',
            name='tlfofi',
            field=models.CharField(default='', max_length=150, verbose_name='Telf. Ofic.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamotienda',
            name='unidad',
            field=models.CharField(default='', max_length=150, verbose_name='Unidad/Dependencia donde labora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamoordinario',
            name='cantidad_letras',
            field=models.CharField(max_length=150, verbose_name='Cantidad en Letras'),
        ),
        migrations.AlterField(
            model_name='prestamoordinario',
            name='cantidad_numeros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad en Numeros'),
        ),
        migrations.AlterField(
            model_name='prestamotienda',
            name='cantidad_letras',
            field=models.CharField(max_length=150, verbose_name='Cantidad en Letras'),
        ),
        migrations.AlterField(
            model_name='prestamotienda',
            name='cantidad_numeros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad en Numeros'),
        ),
    ]
