# Generated by Django 2.2.10 on 2020-05-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20200507_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamotienda',
            name='faxofi',
            field=models.CharField(max_length=150, verbose_name='Telf. Celular'),
        ),
        migrations.AlterField(
            model_name='prestamotienda',
            name='tlfofi',
            field=models.CharField(max_length=150, verbose_name='Telf. Local.'),
        ),
    ]
