# Generated by Django 2.2.10 on 2020-05-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_tipoprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamotienda',
            name='casa_comercial',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Casa Comercial'),
        ),
    ]
