# Generated by Django 2.2.10 on 2020-05-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_auto_20200508_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprestamo',
            options={'verbose_name': 'Tipo de Prestamo', 'verbose_name_plural': 'Tipos de Prestamos'},
        ),
    ]
