# Generated by Django 2.2.10 on 2020-05-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_auto_20200509_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamotienda',
            name='tipo_prestamo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicios.TipoPrestamo', verbose_name='Tipo de Prestamo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Tipo de Prestamo'),
        ),
    ]
