# Generated by Django 2.2.10 on 2020-05-09 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20200509_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamotienda',
            name='cantidad_numeros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.DecimalValidator(15, 2)], verbose_name='Cantidad en Numeros'),
        ),
    ]
