# Generated by Django 2.2.10 on 2020-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_auto_20200509_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamotienda',
            name='cantidad_numeros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad en Numeros'),
        ),
    ]
