# Generated by Django 2.2.10 on 2020-05-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_auto_20200509_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamoafianzado',
            options={'ordering': ['user'], 'verbose_name': 'Préstamo Afianzado', 'verbose_name_plural': 'Préstamos Afianzados'},
        ),
    ]
