# Generated by Django 2.2.10 on 2020-05-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_auto_20200511_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprestamo',
            options={'verbose_name': 'Tipo de Préstamo', 'verbose_name_plural': 'Tipos de Préstamos'},
        ),
    ]
