# Generated by Django 2.2.10 on 2020-05-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_auto_20200512_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamotienda',
            name='faxofi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telf. Celular'),
        ),
        migrations.AlterField(
            model_name='prestamotienda',
            name='tlfofi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telf. Local.'),
        ),
    ]
