# Generated by Django 2.2.10 on 2020-03-01 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200301_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estruc_org',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Estructura Organizacional'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='producto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Producto'),
        ),
    ]
