# Generated by Django 2.2.10 on 2020-03-01 11:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20200301_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mision'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='vision'),
        ),
    ]
