# Generated by Django 2.2.10 on 2020-03-01 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20200301_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='producto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Productos/Servicios'),
        ),
    ]
