# Generated by Django 2.2.10 on 2020-03-03 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20200301_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='visión'),
        ),
    ]
